version: 2
updates:
  - package-ecosystem: "poetry" 
    directory: "/" 
    schedule:
      interval: "daily"

      - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

