name: Mon Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Utilisez Python avec Poetry
        uses: ./.github/actions/install-python-with-poetry
