name: My CI Workflow

on:
  pull_request:
  push:
  manual:
    # Add any manual triggers you need

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: curl --retry 3 -L https://semgrep.dev/install.sh | sh

      - name: Run Semgrep
        run: semgrep --config=p/r2c-ci .

  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run make code-quality
        run: make code-quality

  dockerfile_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)" && chmod +x hadolint

      - name: Run Hadolint
        run: ./hadolint Dockerfile

  super_linter:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        with:
          flags: "--exclude ui/templates"
